language: node_js
node_js: node
cache:
  directories:
    - node_modules
deploy:
  provider: heroku
  app: alley-cheetah
  api_key:
    secure: GS3c5qXNXby6CPY4mB7OaUtYyjZiBWNRvHb6MW/lVp+f+gjkHMP7lNL6JJIrIRnKXUn5eL5S0yhaKGIEmrXxxo22syKcbrSkZMtWEZP+vtzqrU9zIRuBRSAhfrbZRXwLSe0my0EmIYNHlEhzJKL1wNXCxoi31IDr79y1pHedmlS2ByFhJZ8A0kSC5dfWIH12rezvt6YiEE9+T35EBJv0hui6wVoSaE6OKYqwWyIpwwrcdl5pjiELIb1/vrCnVqw8Q768e535w3RPUeZE1Cl10plvqTqDCMgq7/kTVUv+oZVtzwNy1MD+HO7X9EnzgXifuYiSPy+zGhjIdVZliq759vNWoRvZNyJXxFgRvRWq5lX5X91CmaBBVgwGgtxCPqlrdBqoPeq1nIt06u9DLZWTXNAMPgo7NwnFpHcwPmAURc4VaqxK17I7Q1o/+ncHWFU8rbL/n6OZeQZnfPtkv/GZDV/hTd0oTlH1Lcv+nLL419rP1Cty6TAzBlxKVIbgB50AcESv9v3uakqD1aNgd6cJheER9V8pkyJuVhLUMHw4NuJB2wnfgvotzoBp9vBFEwKbjpM5vbve63UTMQxJk6IR4nCI5TPoP9qDwblrDvBlR0NSQAZ20CA90tqO5OsqbwuMDO7RjLA1VeCqqL+qUnJIKxMr1wW923b0h+lgG9e5WuI=
