language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  app: alley-cheetah
  api_key:
    secure: LNEJU5asw6yL7BeRN6NOZ3syyJU3VpVlbWH5x/Fa+5EamsFM28zITqldUFvHgpVPR5MdBv+MtKnSTt1eoDH6lLgrOkXpclshJ+XFYx9s3brwBkODz9rG4CK6+IqYhEB/8FZ9ejT3p0fNAccPEw8twNh1tNoxG4S4aVcBIkcEomjO/PebjE3sQbX7bjvz10gmw7dNJRBB5yfddFzmKS0H+W74QQh8EGk6BRzpDK7wux+Ps/01WwAVtgF2Oout0yMSwG9lofVjItJ81mPptnemdXZ1IS9GdQLqHUicAvPLSgozt07HeOQOn8T7cyNFNb2ddVGBf2Yaqf5l2SbjEA2xPc6ELqXZ/ohGBIyh24ezN5AOY465pPowYqOZSnWLonTNTXygduPqx6nvZt4KAO5dqS4aWWJMv3iEQQQO2ZPzdlXiO8FxZg+VBz/MPjqoKJmt1AYXZBKA/ZD1+6ZDUaxWDKxqsOp5YmtnaoS91iPf4A0pQzcAJWjNIFHlRilAGs8sjTSAGdgji6aDNodXm7B2Y+ksQpfaBwbRKzmWolrDva8P//3te6Ovi0YB2/GntSWsjA2U6guOTfftQxOjRizq/fvb4fHG+XB0rEsSfNTG0qhlAQ+jotldy4ZWMxPkDpRmG+i2KmM/+2Kn884QpsCIkuomMb3iJXPm56UiIJ1K0d4=
